JE_ExceptionTransformer caused a NoClassDefFoundError with versions of BDB-JE older than 4.0
git-svn-id: https://carbonado.svn.sourceforge.net/svnroot/carbonado/trunk@1367 10d2b956-6817-0410-83da-9bc979dc7b36